In [1]:
import numpy as np

In [34]:
array = np.array([
    [5,0,0,0],
    [5,0,0,0],
    [5,0,0,0],
    [5,0,0,0]
])

In [30]:
derv = np.gradient(array)[0]
derv

array([[ 0. , -1. ,  0. ,  0. ],
       [ 0. ,  0.5,  0. ,  0. ],
       [ 0. , -1. ,  0. ,  0. ],
       [ 0. , -4. ,  0. ,  0. ]])

In [35]:
print array
for i in range(5):
    derv = np.gradient(array)
    array = array + derv[0] + derv[1]
    print array


[[5 0 0 0]
 [5 0 0 0]
 [5 0 0 0]
 [5 0 0 0]]
[[ 0.  -2.5  0.   0. ]
 [ 0.  -2.5  0.   0. ]
 [ 0.  -2.5  0.   0. ]
 [ 0.  -2.5  0.   0. ]]
[[-2.5  -2.5   1.25  0.  ]
 [-2.5  -2.5   1.25  0.  ]
 [-2.5  -2.5   1.25  0.  ]
 [-2.5  -2.5   1.25  0.  ]]
[[-2.5   -0.625  2.5   -1.25 ]
 [-2.5   -0.625  2.5   -1.25 ]
 [-2.5   -0.625  2.5   -1.25 ]
 [-2.5   -0.625  2.5   -1.25 ]]
[[-0.625   1.875   2.1875 -5.    ]
 [-0.625   1.875   2.1875 -5.    ]
 [-0.625   1.875   2.1875 -5.    ]
 [-0.625   1.875   2.1875 -5.    ]]
[[  1.875     3.28125  -1.25    -12.1875 ]
 [  1.875     3.28125  -1.25    -12.1875 ]
 [  1.875     3.28125  -1.25    -12.1875 ]
 [  1.875     3.28125  -1.25    -12.1875 ]]
